# Config file for automatic testing at travis-ci.org

language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"

install:
  - "pip install -e ."
  - "pip install -r requirements.txt"

script:
  - "py.test"
  - "cd skyfield/documentation && make doctest"
