# Config file for automatic testing at travis-ci.org

language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"

install:
  - "pip install -e ."
  - "pip install -r requirements.txt"
  - "pip install https://github.com/brandon-rhodes/assay/archive/master.zip"

script:
  - "pip install unittest2"
  - "assay --batch skyfield.tests"
  - "cd skyfield/documentation && make doctest"
