# Config file for automatic testing at travis-ci.org

language: python
sudo: false

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - "python setup.py sdist"
  - "pip install dist/skyfield-*.tar.gz[tests]"
  - "pip install https://github.com/brandon-rhodes/assay/archive/master.zip"
  - "pip install unittest2"
  - "mkdir tmp"
  - "cd tmp && curl -O ftp://ssd.jpl.nasa.gov/pub/eph/planets/bsp/de405.bsp"
  - "cd tmp && curl -O ftp://ssd.jpl.nasa.gov/pub/eph/planets/bsp/de421.bsp"
  - "cd tmp && curl -O ftp://naif.jpl.nasa.gov/pub/naif/generic_kernels/spk/satellites/jup310.bsp"

script:
  - "cd tmp && assay --batch skyfield.tests"
