# Config file for automatic testing at travis-ci.org

language: python
sudo: false

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - "./requirements.sh"
  - "pip install -e ."
  - "pip install https://github.com/brandon-rhodes/assay/archive/master.zip"

script:
  - "pip install unittest2"
  - "assay --batch skyfield.tests"
  - "ln *.bsp skyfield/documentation"
#  - "if [ $TRAVIS_PYTHON_VERSION != 2.6 ] && [ $TRAVIS_PYTHON_VERSION != 3.3 ] ; then make -C skyfield/documentation doctest; fi"
